require File.expand_path('../lib/version.rb', __FILE__)

Gem::Specification.new do |gem|

  gem.name        = 'gcovtools'
  gem.version     = GCOVTOOLS::VERSION
  gem.date        = '2014-12-09'
  gem.summary     = "gcov parser and formatter"
  gem.description = "gcovtools digests .gcov files generated by llvm-cov and translates them into various common formats"
  gem.authors     = ["Mattias Bergbom"]
  gem.email       = 'mattias.bergbom@gmail.com'
  gem.files       = `git ls-files`.split($\)
  gem.executables = ["gcovtools"]
  gem.homepage    = 'http://rubygems.org/gems/gcovtools'
  gem.license     = 'MIT'
  gem.required_ruby_version = '>= 2.0'

  gem.add_development_dependency 'rspec', '~> 3.1', '>= 3.1.0'
  gem.add_development_dependency 'rake', '~> 10.4', '>= 10.4.2'
  gem.add_development_dependency 'rubygems-tasks', '~> 0.2', '>= 0.2.4'
  gem.add_development_dependency 'simplecov', '~> 0.9', '>= 0.9.1'
  
  gem.add_runtime_dependency 'terminal-table', '~> 1.4', '>= 1.4.5'
  gem.add_runtime_dependency 'term-ansicolor', '~> 1.3', '>= 1.3.0'
  gem.add_runtime_dependency 'thor', '~> 0.19', '>= 0.19.1'
  gem.add_runtime_dependency 'gyoku', '~> 1.0'

end
